name: build-deploy-usdr-gost

on:
  push:
    branches:
      - main
      - _staging
    tags:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Server tests
        run: npm run test
