# name: build-deploy-usdr-gost

# on:
#   push:
#     branches:
#       - main
#       - _staging
#     tags:
#       - "**"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: npm ci
#       - name: Run Linter
#         run: npm run lint
#       - name: Run Server tests
#         run: npm run test

on:
  pull_request: {}
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

name: Continuous Integration

jobs:
  test-server-client:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:13"
        env:
          POSTGRES_DB: "usdr_grants_test"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "password"
          POSTGRES_TEST_URL: "postgresql://postgres:password@localhost:5432/usdr_grants_test"
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: "yarn setup"

      - name: Run Linter
        run: |
          yarn lint

      - name: Run unit tests
        env:
          POSTGRES_TEST_URL: "postgresql://postgres:password@localhost:5432/usdr_grants_test"
          AWS_ACCESS_KEY_ID: "Fake AWS Key"
          AWS_SECRET_ACCESS_KEY: "Fake AWS Secret"
          NOTIFICATIONS_EMAIL: "grants-identification@usdigitalresponse.org"
        run: |
          # The .env file needs to be present; the example file is good enough.
          cp .env.example .env
          yarn test
